### PR TITLE
[feat, refactor]: Support to config default theme

### PR DESCRIPTION
**Pull request by nfl1ryxditimo12**
### 1. Unify scattered Scheme type declarations
- The scattered `Scheme` type declaration was integrated into the `src/types/index.ts` path. 345da8991f2223be563d897407b92933debf50a4

### 2. Simplify ternary operator
- `Scheme` has been integrated and the ternary operation has been removed as it is unnecessary. 4cc70c0af57191d582d238c2f18f57eca9858125

### 3. Support to config default theme
- Added `scheme` property to set blog theme to `site.config.js` file. 259efc013ce2d222bda7b985ba43e7cbe02cf2bf

### 4. Auto mode according to the system theme
- Added `followSystemTheme` property that change themes based on system settings 4b4a0d0f2d75f4eca78879880ded004cb22dc806

<br>

## Usage

[site.config.js #L23-24](https://github.com/nfl1ryxditimo12/morethan-log/blob/4b4a0d0f2d75f4eca78879880ded004cb22dc806/site.config.js#L23-L24)

스크린샷 2024-05-03 03 26 01

> 1. If you want to choose `light` mode as the default theme, please write that. default value is `dark`.
>
> 2. If `followSystemTheme` is true, the appearance will be changed according to the system theme on first visit your blog. After that, follow the cookie settings.

<br>

### Light mode

Frame 133999 (1)

### Dark mode

Frame 133998 (1)

### Auto mode (Base on system appearance)

Frame 134000 (2)

<br>

## Related tickets

https://github.com/morethanmin/morethan-log/issues/XX

<br>

## PR Checklist

- [x] I have read the [Contributing Guide](./docs/CONTRIBUTING.md)
- [x] I have written documents and tests, if needed.

### CODE REVIEW

**Comment by nfl1ryxditimo12** [comment]
리뷰어 지정해서 다시 열겠습니다 🙏

**Comment by nfl1ryxditimo12** [comment]
@morethanmin PR 확인 부탁드려요~!

**Comment by nfl1ryxditimo12** [comment]
추가 했습니다 🫡

**Review by morethanmin — APPROVED** [review]
감사합니다!

**Pull request merged**
