### PR TITLE
Enabling Dark Mode

### PR DESCRIPTION
**Pull request by kvaishak**
PR for the following changes. 
1. Enabling Dark Mode. [ Issue #20 ]
2. Removing the Horizontal scroll bar for Tags in Desktop view.
image

Now Horizontal scroll bar wont be visible for desktop view, but only for mobile view.

### CODE REVIEW

**Review by morethanmin — CHANGES_REQUESTED** [review]
Thank you very much for your PR! As you can see in the picture, dark mode requires color settings.

Therefore, in order to enalbe the dark mode, color settings for the dark mode are also required.

image

**Comment by kvaishak** [comment]
> Thank you very much for your PR! As you can see in the picture, dark mode requires color settings.
> 
> Therefore, in order to enalbe the dark mode, color settings for the dark mode are also required.
> 
> image

That is weird, I didn't see any issues in my local development, with the above changes. 🤔 
image

Please check my deployed Vercel version too. https://notes-git-dark-mode-kvaishak.vercel.app/

**Comment by kvaishak** [comment]
@morethanmin  PS, I have mistakenly merged my main branch to the Branch `dark-mode` so Please ignore this PR.
I will be creating a new PR with just the changes to be merged. Sorry for the confusion.

**Review by morethanmin — CHANGES_REQUESTED** [review]
Oh I see. Please reqeust again and I'll approve it. :)

**Pull request closed without merging**
